; 1 worker can handle 1024 connections same time
events {
    worker_connections 1024;
}

; Proxy Route Sample
; location /api/ {
;     proxy_pass http://localhost:3000;
;     proxy_set_header Host $host;
;     }

http {
  server {
    listen 80; //connect port 80

    # TODO (W2 D6): route /api/users/* -> user-service:8002
    location /api/users/ {

        proxy_pass http://user-service:8002; // = http://localhost/api/users
        proxy_set_header Host $host; // forward host header tell backend where request came from
        proxy_set_header X-Real-IP $remote_addr; // get real client IP
    }

    # TODO (W2 D6): route /api/questions/* -> question-management-service:8003
    location /api/users/ {

      proxy_pass http://question-management-service:8003;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # TODO (W2 D6): route /api/sessions/* -> test-management-service:8001
    location /api/sessions/ {
        proxy_pass http://test-management-service:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # TODO (W2 D6): default fallback to frontend:3000
    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      return 502 "Reverse proxy not yet configured. See nginx.conf TODO.";
    }
  }
}
